name: et_rr
channels:
  - pytorch
  - plotly
  - anaconda
  - huggingface
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas>2.0.1
  - seaborn=0.13
  - matplotlib=3.8
  - numpy=1.26
  - plotly
  - pyyaml
  - pynvml # for checking gpu utilization
  - datasets=2.18
  - scikit-learn=1.4
  - pip
  - wordfreq=3.1
  - wandb=0.16
  - pre-commit
  - ruff
  - hydra-core=1.3
  - ipykernel
  - mypy
  - pandas-stubs # for type checking
  - types-tqdm # for type checking
  - typed-argument-parser
  - pip:
      - git+https://github.com/lacclab/process-onestop-sr-report.git # if using ssh-key note to change this and all repos in the way
      - git+https://github.com/lacclab/text-metrics.git
      - rich
      - julia # python3 -m pip install julia
